### ISSUE TITLE
Enhance API design of tonaparser

### ISSUE THREAD

**Issue by arowM** [tonatona-project/tonatona#24]
This was explained in https://github.com/arow-oss/tonatona/pull/20#issuecomment-413134750

**Comment by cdepillabout** [comment]
This probably encompasses #23.

**Comment by cdepillabout** [comment]
I added a comment with what I thought would be a better design of tonaparser to work like optparse-applicative:

https://github.com/arow-oss/tonatona/issues/27#issuecomment-414957917

**Comment by cdepillabout** [comment]
This completely emcompasses #23 and #22 (see https://github.com/arow-oss/tonatona/issues/27#issuecomment-414957917), so I will close them in favor of this issue.
